Vertical Candidate List=False
WheelForPaging=True
Font="Sans Serif 15"
MenuFont="Sans 10"
TrayFont="Sans Bold 10"
Theme=default-dark
DarkTheme=default-dark
UseDarkTheme=False
UseAccentColor=True
EnableFractionalScale=True
